services:
  mydb:
    image: mysql
    restart: always
    container_name: db
    ports:
     - 3308:3306
    environment:
      MYSQL_DATABASE: ollama_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
     - ./dump:/docker-entrypoint-initdb.d   
  app:
      container_name: py-app
      links:
        - "mydb:database"
      build: ./
  ai:
      image: myollama
      container_name: ai-myollama
      ports:
        - "11435:11434"